import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Cleanup old caches automatically
cleanupOutdatedCaches();

// Precache all assets generated by Vite build
precacheAndRoute(self.__WB_MANIFEST || []);

// 1. Cache-First strategy for images, icons and PWA assets
registerRoute(
  ({ request, url }) => 
    request.destination === 'image' || 
    url.pathname.endsWith('.png') || 
    url.pathname.endsWith('.svg') || 
    url.pathname.endsWith('.ico') || 
    url.pathname.endsWith('.jpg') || 
    url.pathname.endsWith('.jpeg') || 
    url.pathname.endsWith('.webp') ||
    url.pathname.includes('/pwa-') ||
    url.pathname.includes('apple-touch-icon') ||
    url.pathname.includes('mask-icon'),
  new CacheFirst({
    cacheName: 'images-and-icons-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// 2. Cache-First strategy for static resources (CSS, JS, Web Fonts, Manifest)
registerRoute(
  ({ request, url }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'font' ||
    url.pathname.endsWith('.css') ||
    url.pathname.endsWith('.js') ||
    url.pathname.endsWith('.webmanifest') ||
    url.pathname.endsWith('.woff2') ||
    url.pathname.endsWith('.woff'),
  new CacheFirst({
    cacheName: 'static-resources-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
      }),
    ],
  })
);

// 3. NetworkFirst for API GET requests with offline fallback
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  }),
  'GET'
);

// Background sync for mutating shopping lists and items
const bgSyncPlugin = new BackgroundSyncPlugin('shopping-lists-queue', {
  maxRetentionTime: 24 * 60 // 24 hours
});

registerRoute(
  ({ url }) => url.pathname.includes('/api/shopping-lists') || url.pathname.includes('/api/shopping-items'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

registerRoute(
  ({ url }) => url.pathname.includes('/api/shopping-lists') || url.pathname.includes('/api/shopping-items'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'PUT'
);

registerRoute(
  ({ url }) => url.pathname.includes('/api/shopping-lists') || url.pathname.includes('/api/shopping-items'),
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'DELETE'
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

self.addEventListener('push', (event: any) => {
  const data = event.data ? event.data.json() : { title: 'Alerta Financeiro', body: 'Você tem transações pendentes!' };
  
  const options = {
    body: data.body,
    icon: '/pwa-192x192.png',
    badge: '/mask-icon.svg',
    vibrate: [200, 100, 200],
    tag: data.tag || 'recurring-alert',
    data: data.url || '/'
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  event.waitUntil(
    (self.clients as any).openWindow(event.notification.data || '/')
  );
});

